services:
  laravel.test:
    build:
      context: './vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      # REMOVIDO: '8080:8080' (porta exposta no serviço reverb)
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql

  reverb:
    image: 'sail-8.4/app'         # mesma imagem do laravel.test
    working_dir: /var/www/html
    depends_on:
      - laravel.test
    environment:
      WWWUSER: '${WWWUSER:-1000}'  # garante que não será 0
      LARAVEL_SAIL: 1
      HOME: '/home/sail'
      COMPOSER_HOME: '/home/sail/.composer'
    volumes:
      - '.:/var/www/html'
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    restart: unless-stopped
    networks:
      - sail
    ports:
      - '8080:8080'
    healthcheck:
      # testa se a porta 8080 está aceitando conexões (sem depender de bash/nc)
      test: ["CMD", "php", "-r", "exit((int)!@fsockopen('127.0.0.1', 8080));"]
      interval: 10s
      timeout: 3s
      retries: 5

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local